STATE_CODES = {}
STATE_CODES["AP"] <- 'Andhra Pradesh'
STATE_CODES["AR"] <- 'Arunachal Pradesh'
STATE_CODES["AS"] <- 'Assam'
STATE_CODES["BR"] <- 'Bihar'
STATE_CODES["CT"] <- 'Chhattisgarh'
STATE_CODES["GA"] <- 'Goa'
STATE_CODES["GJ"] <- 'Gujarat'
STATE_CODES["HR"] <- 'Haryana'
STATE_CODES["HP"] <- 'Himachal Pradesh'
STATE_CODES["JH"] <- 'Jharkhand'
STATE_CODES["KA"] <- 'Karnataka'
STATE_CODES["KL"] <- 'Kerala'
STATE_CODES["MP"] <- 'Madhya Pradesh'
STATE_CODES["MH"] <- 'Maharashtra'
STATE_CODES["MN"] <- 'Manipur'
STATE_CODES["ML"] <- 'Meghalaya'
STATE_CODES["MZ"] <- 'Mizoram'
STATE_CODES["NL"] <- 'Nagaland'
STATE_CODES["OR"] <- 'Odisha'
STATE_CODES["PB"] <- 'Punjab'
STATE_CODES["RJ"] <- 'Rajasthan'
STATE_CODES["SK"] <- 'Sikkim'
STATE_CODES["TN"] <- 'Tamil Nadu'
STATE_CODES["TG"] <- 'Telangana'
STATE_CODES["TR"] <- 'Tripura'
STATE_CODES["UT"] <- 'Uttarakhand'
STATE_CODES["UP"] <- 'Uttar Pradesh'
STATE_CODES["WB"] <- 'West Bengal'
STATE_CODES["AN"] <- 'Andaman and Nicobar Islands'
STATE_CODES["CH"] <- 'Chandigarh'
STATE_CODES["DN"] <- 'Dadra and Nagar Haveli and Daman and Diu'
STATE_CODES["DL"] <- 'Delhi'
STATE_CODES["JK"] <- 'Jammu and Kashmir'
STATE_CODES["LA"] <- 'Ladakh'
STATE_CODES["LD"] <- 'Lakshadweep'
STATE_CODES["PY"] <- 'Puducherry'
STATE_CODES["TT"] <- 'India'
